config/routes.rb
Rails.application.routes.draw do
  root "publications#index"
  
  post '/new_user_reaction', to: 'reactions#new_user_reaction', as: 'new_user_reaction'

  resources :comments, only: [:create]
  resources :publications do
    resources :comments, only: [:create] # Permite crear comentarios para una publicación específica
  end


  devise_for :users

  # Health check and PWA routes
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  def likes_count
    reactions.where(kind: 'like').count
  end

  def dislikes_count
    reactions.where(kind: 'dislike').count
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :publication, optional: true
  belongs_to :comment, optional: true

  validates :kind, inclusion: { in: %w[like dislike] } # Asegúrate de que sea 'like' o 'dislike'
  validates :reaction_type, presence: true # Asegúrate de que reaction_type esté en la base de datos

  # Método para obtener los tipos de reacción
  def self.kinds
    %w[like dislike]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :publications
  has_many :reactions
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name ])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @publication = Publication.find(params[:comment][:publication_id])
    @comment = @publication.comments.new(comment_params) # Asociación correcta

    @comment.user = current_user # Asignar el usuario actual

    respond_to do |format|
      if @comment.save
        format.html { redirect_to publication_path(@publication), notice: 'Comment was successfully created.' }
      else
        # En caso de error, renderiza la vista de la publicación con los errores
        format.html { redirect_to publication_path(@publication), alert: 'Comment was not created.' }
        # Puedes optar por renderizar una vista específica si lo prefieres
        # format.html { render 'publications/show', status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :publication_id)
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]


  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @comment = Comment.new
    @comments = @publication.comments.order(id: :desc)
  end


  # GET /publications/new
  def new
    @publication = Publication.new
    @user = current_user
    @comments = Comment.new
  end

  # GET /publications/1/edit
  def edit
    @comment = Comment.new
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy!

    respond_to do |format|
      format.html { redirect_to publications_path, status: :see_other, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:photo, :title, :body)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    def new_user_reaction
      @user = current_user
      @type = params[:reaction_type]
      @publication = Publication.find(params[:publication_id]) if params[:publication_id]
      @comment = Comment.find(params[:comment_id]) if params[:comment_id]
      @kind = params[:kind]
      
      respond_to do |format|
        reaction_publication = Reaction.find_by(user_id: @user.id, publication_id: @publication.id) if @type == "publication"
        reaction_comment = Reaction.find_by(user_id: @user.id, comment_id: @comment.id) if @type == "comment"
  
        if reaction_publication || reaction_comment
          format.html { redirect_to publication_path(@publication), notice: 'You already reacted to this publication' }
        else
          @reaction = if @type == "publication"
                        Reaction.new(user_id: @user.id, publication_id: @publication.id, reaction_type: @type, kind: @kind)
                      else
                        Reaction.new(user_id: @user.id, comment_id: @comment.id, reaction_type: @type, kind: @kind)
                      end
  
          if @reaction.save
            format.html { redirect_to publication_path(@publication), notice: 'Reaction was successfully created.' }
          else
            format.html { redirect_to publication_path(@publication), notice: 'Something went wrong' }
          end
        end
      end
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/reaction_helper.rb
module ReactionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<h6>Comentarios:</h6>
<ul>
  <% publication.comments.each do |comment| %>
    <li><strong><%= comment.user.name %>:</strong> <%= comment.content %></li>
  <% end %>
</ul>

<!-- Incluir el formulario de comentarios -->
<%= render 'comments/form', publication: publication %>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>Este comentario no se pudo crear por las siguientes razones:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <%= f.hidden_field :publication_id, value: @publication.id %>
<div class='field'>
  <%= f.label :content, "Contenido" %>
  <%= f.text_field :content %>
  <div class='actions'>
    <%= f.submit "Enviar", class: "btn btn-primary" %> <!-- Cambiado a un botón de Bootstrap -->
  </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crazy4 Cats" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/b3e35b3c01.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/shared/navbar' %>

    <%= yield %>

    <%= render 'layouts/shared/footer'%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="bg-light text-center py-3 mt-5">
  <div class="container">
    <p>&copy; <%= Time.now.year %> Crazy4Cats, DESAFIO LATAM.</p>
    <div>
    <a href="https://github.com/mrSpeedle/C4C" target="_blank" class="mx-3">
      <i class="fab fa-github fa-2x"></i>
    </a>
    <a href="https://www.youtube.com/watch?v=izGwDsrQ1eQ" target="_blank" class="mx-3">
      <i class="fab fa-youtube fa-2x"></i>
    </a>
    <a href="https://discord.gg/FjXgshGW" target="_blank" class="mx-3">
      <i class="fab fa-discord fa-2x"></i>
    </a>
  </div>
  </div>
</footer>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg custom-navbar">
  <div class="container">
    <a class="navbar-brand" href="/">Mi Aplicación</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Inicio', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Publicaciones', publications_path, class: 'nav-link' %>
        </li>
      </ul>

      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-dark custom-dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            Bienvenido, <%= current_user.email %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="userDropdown">
            <li><%= button_to 'Ver tu cuenta', edit_user_registration_path, method: :get, class: 'dropdown-item' %></li>
            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
          </ul>
        </div>
      <% else %>
        <div class="navbar-text">
          No tienes una cuenta? <%= link_to 'Regístrate aquí', new_user_registration_path, class: 'nav-link' %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div class="container-fluid d-flex justify-content-center">
  <div class="row">
    <div class="col-md-12">
      <div id="<%= dom_id publication %>" class="card mb-4 d-flex flex-row">
        <div class="card-body d-flex flex-column">
          <div class="d-flex">
            <div class="me-3">
              <%= image_tag publication.photo, class: 'img-fluid' %>
            </div>
            <div>
              <h5 class="card-title"><%= publication.title %></h5>
              <p class="card-text"><%= publication.body %></p>
              <div class="d-flex justify-content-between mt-3 pt-4">
                <p>Likes: <%= publication.likes_count %></p>
                <p>Dislikes: <%= publication.dislikes_count %></p>
              </div>
            </div>
          </div>
          <%= link_to "Show this publication", publication_path(publication), class: "btn btn-primary mt-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<% content_for :title, "Editing publication" %>

<h1>Editing publication</h1>

<%= render "comments/form", comment: @comment %>


<br>

<div class="text-center mt-3">
  <%= link_to "Show this publication", @publication, class: "btn btn-primary" %>
  <%= link_to "Back to publications", publications_path, class: "btn btn-secondary" %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Publications" %>

<div class="d-flex justify-content-center align-items-center my-4"> <!-- Contenedor flex centrado -->
  <h1 class="mb-0 me-3">Publications</h1> <!-- Margen a la derecha del h1 -->
  <%= link_to "Nueva Publicación", new_publication_path, class: "btn btn-primary" %> <!-- Botón de Bootstrap -->
</div>

<div id="publications" class="text-center"> <!-- Centro las publicaciones -->
  <% @publications.each do |publication| %>
    <div class="publication-card">
      <%= render publication %>
    </div>
  <% end %>
</div>

app/views/publications/new.html.erb
<% content_for :title, "New publication" %>

<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @publication %>
<div class="d-flex justify-content-center mt-3">
  <div class="me-3">
    <%= link_to "Edit this publication", edit_publication_path(@publication), class: "btn btn-secondary me-2" %>
    <%= link_to "Back to publications", publications_path, class: "btn btn-secondary me-2" %>
    <%= button_to "Destroy this publication", @publication, method: :delete, class: "btn btn-danger me-2" %>
  </div>
  <div>
    <% Reaction.kinds.each do |kind| %>
      <%= button_to "#{kind.capitalize}", new_user_reaction_path(publication_id: @publication.id, reaction_type: "publication", kind: kind), method: :post, class: "btn btn-outline-primary me-2" %>
    <% end %>
  </div>
</div>


<h6>Comentarios:</h6>
<%= render 'comments/form', comment: @comment %>

<ul data-lista-comentarios class="container-fluid p-3">
  <% @comments.each do |comment| %>
  <div class="comentarioEnShow">
    <li><strong><%= comment.user.name %>:</strong>
    <br>
    <%= comment.content %></li>
  </div>
  <% end %>
</ul>